apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-chat-6
  janus-idp.io/tekton: test-chat-6
  backstage.io/kubernetes-id: test-chat-6
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-chat-6
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
