apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-chat-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chat-6 
  name: test-chat-6
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-chat-6 
